[deployment]
run = ["node", "deployment-server.js"]
deploymentTarget = "cloudrun"

[nix]
channel = "stable-22_11"

[env]
PORT = "5000"
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80